import React from 'react';
import { SectionHeading } from '../components/ui/SectionHeading';
import { Card } from '../components/ui/Card';
import { HardHat, ShieldCheck, Cpu } from 'lucide-react';

export const AboutPage = () => {
  return (
    <div className="pt-32 pb-24 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-20">
      
      <SectionHeading
        eyebrow="OUR MISSION & VISION"
        title="Pioneering Autonomous"
        highlightText="Construction Project Intelligence"
        description="ProSight AI was founded by veteran construction planning engineer and AI researchers to solve the global construction inefficiency crisis."
      />

      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
        <Card className="p-8 space-y-4">
          <div className="w-12 h-12 rounded-xl bg-cyan-500/10 border border-cyan-500/30 flex items-center justify-center text-cyan-600">
            <HardHat className="w-6 h-6" />
          </div>
          <h3 className="text-xl font-bold text-slate-900">Built for Builders</h3>
          <p className="text-sm text-slate-600 leading-relaxed">
            We understand site realities — submittals, RFI loops, Primavera delays, and contractor claims. Our AI speaks construction.
          </p>
        </Card>

        <Card className="p-8 space-y-4">
          <div className="w-12 h-12 rounded-xl bg-blue-500/10 border border-blue-500/30 flex items-center justify-center text-blue-600">
            <Cpu className="w-6 h-6" />
          </div>
          <h3 className="text-xl font-bold text-slate-900">Zero Hallucinations</h3>
          <p className="text-sm text-slate-600 leading-relaxed">
            Every answer generated by ProSight AI includes verifiable page citations from your exact uploaded PDF blueprints and BOQs.
          </p>
        </Card>

        <Card className="p-8 space-y-4">
          <div className="w-12 h-12 rounded-xl bg-purple-500/10 border border-purple-500/30 flex items-center justify-center text-purple-600">
            <ShieldCheck className="w-6 h-6" />
          </div>
          <h3 className="text-xl font-bold text-slate-900">Enterprise Security</h3>
          <p className="text-sm text-slate-600 leading-relaxed">
            SOC2 Type II certified. Your proprietary project IP stays completely private in dedicated tenant vector vaults.
          </p>
        </Card>
      </div>

    </div>
  );
};
