import fs from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
const {PGlite}=await import(process.env.PGLITE_MODULE ? pathToFileURL(process.env.PGLITE_MODULE).href : '../outputs/controls-sql-test/node_modules/@electric-sql/pglite/dist/index.js');
const db=new PGlite();
const foundation=await fs.readFile('supabase/migrations/202609110001_prosight_foundation.sql','utf8');
await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;create type public.app_role as enum ('employee','project_manager','planning_engineer','admin');`);
for(const name of ['profiles','projects','project_memberships','change_requests','audit_events','notifications']){
 const match=foundation.match(new RegExp('create table if not exists public\\.'+name+' \\([\\s\\S]*?\\n\\);'));
 if(!match)throw Error('Missing foundation table '+name);await db.exec(match[0]);
}
await db.exec(foundation.slice(foundation.indexOf('create or replace function public.current_app_role()'),foundation.indexOf('create or replace function public.handle_new_user()')));
await db.exec(await fs.readFile('supabase/migrations/202609130001_project_controls.sql','utf8'));
await db.exec(await fs.readFile('supabase/migrations/202609130002_controls_workers.sql','utf8'));
await db.exec(`create schema storage;create table storage.objects(id uuid,name text,bucket_id text);create function storage.foldername(name text) returns text[] language sql as $$select string_to_array(name,'/')$$;`);
await db.exec(await fs.readFile('supabase/migrations/202609130003_controls_batches_exports.sql','utf8'));
console.log('PASS migrations execute in isolated PostgreSQL');
await db.exec(`insert into auth.users values ('11111111-1111-1111-1111-111111111111'),('22222222-2222-2222-2222-222222222222'),('33333333-3333-3333-3333-333333333333');insert into profiles(id,email,role) values ('11111111-1111-1111-1111-111111111111','admin@example.invalid','admin'),('22222222-2222-2222-2222-222222222222','planner@example.invalid','planning_engineer'),('33333333-3333-3333-3333-333333333333','other@example.invalid','employee');insert into projects(code,name,status,client,location,planned_start,planned_finish,reporting_date) values('TEST-1','Isolated test','future','Test','Test','2027-01-01','2027-12-31','2026-09-12');insert into project_memberships values('22222222-2222-2222-2222-222222222222','TEST-1',now());grant usage on schema public,auth to authenticated;set role authenticated;select set_config('request.jwt.claim.sub','22222222-2222-2222-2222-222222222222',false);`);
const stage=async(checksum,parent=null)=> (await db.query(`select stage_controls_version('TEST-1',$1,'{}','{"reporting_date":"2026-09-12"}','{}',$2) as v`,[parent,checksum])).rows[0].v;
const v=await stage('one');const repeated=await stage('one');if(v.id!==repeated.id)throw Error('Idempotency failed');
const change=(await db.query('select submit_controls_version($1) as c',[v.id])).rows[0].c;
await db.exec(`select set_config('request.jwt.claim.sub','11111111-1111-1111-1111-111111111111',false);`);
await db.query('select decide_controls_version($1,true)',[change.id]);
const active=(await db.query("select id from controls_versions where status='active'")).rows;if(active.length!==1)throw Error('Activation failed');
const v2=await stage('two',v.id);const v3=await stage('three',v.id);
const c2=(await db.query('select submit_controls_version($1) as c',[v2.id])).rows[0].c;const c3=(await db.query('select submit_controls_version($1) as c',[v3.id])).rows[0].c;
await db.query('select decide_controls_version($1,true)',[c2.id]);
let stale=false;try{await db.query('select decide_controls_version($1,true)',[c3.id]);}catch(e){stale=String(e).includes('Active version changed');}if(!stale)throw Error('Stale activation not rejected');
await db.exec(`select set_config('request.jwt.claim.sub','33333333-3333-3333-3333-333333333333',false);`);
if((await db.query('select * from controls_versions')).rows.length)throw Error('Unauthorized version visible');
let denied=false;try{await stage('unauthorized');}catch(e){denied=true;}if(!denied)throw Error('Unauthorized stage succeeded');
console.log('PASS idempotent staging, atomic activation, stale approval rejection, unauthorized reads/writes');
await db.exec(`reset role;select set_config('request.jwt.claim.sub','11111111-1111-1111-1111-111111111111',false);`);
const fixtures=JSON.parse(await fs.readFile('outputs/controls-sql-test/fixtures.json','utf8'));
for(const fixture of fixtures){
 const p=fixture.project;
 await db.query(`insert into projects(code,name,status,client,location,planned_start,planned_finish,reporting_date)values($1,$2,$3,$4,$5,$6,$7,$8)`,[p.code,p.name,p.status,p.client,p.location,p.planned_start,p.planned_finish,p.reporting_date]);
 const staged=(await db.query(`select stage_controls_version($1,null,$2,$3,$4,$5) as v`,[p.code,JSON.stringify(fixture.content),JSON.stringify(fixture.metadata),JSON.stringify(fixture.validation),'fixture-'+p.code])).rows[0].v;
 const cr=(await db.query('select submit_controls_version($1) as c',[staged.id])).rows[0].c;
 await db.query('select decide_controls_version($1,true)',[cr.id]);
 const count=(await db.query('select count(*)::int n from controls_schedule where controls_version_id=$1',[staged.id])).rows[0].n;
 if(count!==(fixture.content.Schedule||[]).length)throw Error('Typed schedule mismatch');
 console.log('PASS typed fixture stage/approve/activate',p.code,count);
}
await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','22222222-2222-2222-2222-222222222222',false);`);
const queued=(await db.query(`insert into controls_jobs(project_code,requested_by,kind,version_id,input)values('TEST-1',auth.uid(),'analyst',$1,'{"query":"Analyze EVM"}') returning *`,[v2.id])).rows[0];
await db.exec('reset role;set role service_role;');
const lease=(await db.query('select claim_controls_job() as j')).rows[0].j;
if(lease.id!==queued.id)throw Error('Job claim failed');
await db.exec(`reset role;update controls_jobs set lease_until=now()-interval '1 second' where id='${lease.id}';set role service_role;`);
const recovered=(await db.query('select claim_controls_job() as j')).rows[0].j;
if(recovered.lease_id===lease.lease_id||recovered.attempts!==2)throw Error('Lease recovery failed');
const staleFinish=(await db.query(`select finish_controls_job($1,$2,'{}','completed',null) as j`,[lease.id,lease.lease_id])).rows[0].j;
if(staleFinish!==null)throw Error('Stale worker finished job');
await db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','22222222-2222-2222-2222-222222222222',false);`);
let scopeDenied=false;try{await db.query(`update controls_jobs set input='{"query":"changed"}' where id=$1`,[lease.id]);}catch(e){scopeDenied=true;}if(!scopeDenied)throw Error('Scope mutation allowed');
await db.query(`update controls_jobs set status='cancelled' where id=$1`,[lease.id]);
await db.exec('reset role;set role service_role;');
if((await db.query(`select finish_controls_job($1,$2,'{}','completed',null) as j`,[lease.id,recovered.lease_id])).rows[0].j!==null)throw Error('Cancelled job finished');
console.log('PASS job lease recovery, stale completion rejection, immutable scope, cancellation');
await db.exec(`reset role;insert into project_memberships(user_id,project_code)values('22222222-2222-2222-2222-222222222222','PRJ-2022-009');select set_config('request.jwt.claim.sub','11111111-1111-1111-1111-111111111111',false);`);
const history=(await db.query("select id from controls_versions where project_code='PRJ-2022-009' and status='active'")).rows[0];
const linked=(await db.query(`select stage_controls_version('TEST-1',$1,$2,'{"reporting_date":"2026-09-12"}','{}','historical') as v`,[v2.id,JSON.stringify({'Historical Sources':[{project_code:'PRJ-2022-009',version_id:history.id}]})])).rows[0].v;
await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','22222222-2222-2222-2222-222222222222',false);`);
const artifact=(await db.query("select create_controls_export($1,'pdf') as a",[linked.id])).rows[0].a;
if((await db.query('select id from controls_artifacts where id=$1',[artifact.id])).rows.length!==1)throw Error('Authorized artifact unavailable');
await db.exec(`reset role;delete from project_memberships where user_id='22222222-2222-2222-2222-222222222222' and project_code='PRJ-2022-009';set role authenticated;`);
if((await db.query('select id from controls_versions where id=$1',[linked.id])).rows.length)throw Error('Historical version leaked after revocation');
if((await db.query('select id from controls_artifacts where id=$1',[artifact.id])).rows.length)throw Error('Historical artifact leaked after revocation');
console.log('PASS historical membership revocation removes version and artifact access');
await db.close();
